services:
  temporal:
    image: temporalio/auto-setup:1.25
    container_name: temporal
    ports:
      - "7233:7233"
    environment:
      - DB=sqlite

  temporal-ui:
    image: temporalio/ui:2.34.0
    container_name: temporal-ui
    ports:
      - "8088:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233